name: PR title validation
on:
  pull_request:
    types: [opened, reopened, edited]
  push:
    branches-ignore:
      - 'master'
      - 'release/**'

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        if: github.event_name == 'push'
      - uses: jwalton/gh-find-current-pr@v1
        if: github.event_name == 'push'
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: bash
        run: |
          TITLE=""
          [[ $TITLE_FROM_PR != "" ]] && TITLE=$TITLE_FROM_PR
          [[ $TITLE_FROM_COMMIT != "" ]] && TITLE=$TITLE_FROM_COMMIT
          [[ $TITLE == "" ]] && exit 0

          [[ "$TITLE" == "hello" ]] && exit 0
          [[ "$TITLE" == "world" ]] && exit 0
          exit 1
        env:
          TITLE_FROM_PR: ${{ github.event.pull_request.title }}
          TITLE_FROM_COMMIT: ${{ steps.findPr.outputs.title }}
